# Steven Luu

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [18]:
# YOUR SOLUTION HERE
import numpy as np
a = np.empty((6,4),dtype= np.int)
a.fill(2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [22]:
# YOUR SOLUTION HERE

b = np.empty((6,4), dtype = np.int)
b.fill(2)
np.fill_diagonal(b, 3)
b

array([[3, 2, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 3, 2],
       [2, 2, 2, 3],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 3

**a * b multiplies the numbers that are in the same spot, but**
**np.dot(a,b) uses actual matrix multiplication, and the dimensions** 
**are not compatible to do so**


## Exercise 4

In [33]:
# YOUR SOLUTION HERE
print(np.dot(a.transpose(),b))
# (6 x 4) * (4 * 6)
#      ^_____^

print(np.dot(a,b.transpose()))
# (4 x 6) * (6 x 4)
#      ^_____^


# The results are different shapes because the inside numbers are
# different from the matrix multiplication

[[26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]]
[[18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]]


## Exercise 5

In [35]:
# YOUR SOLUTION HERE
def printThing():
    print("Hello World!")
    
printThing()

Hello World!


## Exercise 6

In [45]:
# YOUR SOLUTION HERE

def createArrays():
    arr1 = np.random.randint(0, 100, (3, 6, 5))
    arr2 = np.random.randint(0, 100, (3, 6, 5))
    
    print(arr1 + arr2)
    
    
createArrays()
    

[[[128 148 146  67  82]
  [153  52 184  26 122]
  [108 115 139  96  48]
  [168  94  37 109 114]
  [100  80  72 121 118]
  [111  64  57  64 101]]

 [[ 29 131 102  64 133]
  [ 71 140  59 112 186]
  [ 88  95  66 151 132]
  [ 33 108  78  77  75]
  [ 28 101  63  80 134]
  [108 106  28  62 160]]

 [[135 118  99  33 110]
  [ 96 151 192  95 140]
  [103  63  61 147 107]
  [ 82  61  48  66  65]
  [112 122  60  74 125]
  [191 127  17 159  40]]]


## Exercise 7

In [42]:
# YOUR SOLUTION HERE


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE