# Steven Luu

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

1. If you write functions in other notebooks, can you call them across different notebooks?

2. I'm still unsure of when you should use numpy dimensions like (1,1) vs (,1)

3. 

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [159]:
# YOUR SOLUTION HERE
import numpy as np
a = np.empty((6,4),dtype= np.int)
a.fill(2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [160]:
# YOUR SOLUTION HERE

b = np.empty((6,4), dtype = np.int)
b.fill(2)
np.fill_diagonal(b, 3)
b

array([[3, 2, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 3, 2],
       [2, 2, 2, 3],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 3

**a * b multiplies the numbers that are in the same spot, but**
**np.dot(a,b) uses actual matrix multiplication, and the dimensions** 
**are not compatible to do so**


## Exercise 4

In [161]:
# YOUR SOLUTION HERE
print(np.dot(a.transpose(),b))
# (6 x 4) * (4 * 6)
#      ^_____^

print(np.dot(a,b.transpose()))
# (4 x 6) * (6 x 4)
#      ^_____^



# The results are different shapes because the inside numbers are
# different from the matrix multiplication

[[26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]]
[[18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]
 [18 18 18 18 16 16]]


## Exercise 5

In [162]:
# YOUR SOLUTION HERE
def printThing():
    print("Hello World!")
    
printThing()

Hello World!


## Exercise 6

In [165]:
# YOUR SOLUTION HERE

def createArray():
    arr1 = np.random.randint(0, 20, (6, 5))
    
    
    print(arr1)
    print("Mean of Array is: ", arr1.mean())
    print("Sum of Array is: ", arr1.sum())
    
    
createArray()
    

[[ 1  4 19 11  2]
 [16 12 19  0 16]
 [ 7  5  1 16 14]
 [ 9 12  9 17  7]
 [ 1 11 19  8 17]
 [18  5  8  6 12]]
Mean of Array is:  10.066666666666666
Sum of Array is:  302


## Exercise 7

In [166]:
# YOUR SOLUTION HERE
arr1 = np.random.randint(0, 2, (1, 5, 5))
arr1 = arr1.reshape(5,5)
ones = 0
print(arr1)
for row in arr1:
    for value in row:
        if value == 1:
            ones += 1
print(ones)
arr1[np.where(arr1==1)].sum()

[[0 0 0 0 0]
 [1 0 0 0 1]
 [0 0 0 0 0]
 [1 1 1 1 0]
 [0 0 0 1 0]]
7


7

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [167]:
# YOUR SOLUTION HERE
import pandas as pd
a = pd.DataFrame(np.ones((6,4)) * 2)
a

0    1    2    3
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
3  2.0  2.0  2.0  2.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [168]:
# YOUR SOLUTION HERE
b = np.ones((6,4)) * 2
b = pd.DataFrame(b)
b.iloc[range(4),range(4)] =3
b

0    1    2    3
0  3.0  2.0  2.0  2.0
1  2.0  3.0  2.0  2.0
2  2.0  2.0  3.0  2.0
3  2.0  2.0  2.0  3.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [169]:
# YOUR SOLUTION HERE

print(a.multiply(b))
#a.dot(b)

     0    1    2    3
0  6.0  4.0  4.0  4.0
1  4.0  6.0  4.0  4.0
2  4.0  4.0  6.0  4.0
3  4.0  4.0  4.0  6.0
4  4.0  4.0  4.0  4.0
5  4.0  4.0  4.0  4.0


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [170]:
# YOUR SOLUTION HERE
arr1 = np.random.randint(0, 2, (5, 5))
df = pd.DataFrame(arr1)
print(df)
ones = 0
for i in range(len(df)):
    for num in df[i]:
        if num == 1:
            ones += 1
print(ones)
int(df[df == 1].sum().sum())

   0  1  2  3  4
0  1  0  1  1  0
1  0  0  0  1  0
2  1  1  1  1  1
3  1  1  1  0  0
4  1  1  0  1  0
15


15

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [171]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df


pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [172]:
## YOUR SOLUTION HERE
titanic_df.name

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [192]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)
females = titanic_df.loc['female']
len(females)

466

## Exercise 14
How do you reset the index?

In [191]:
## YOUR SOLUTION HERE
titanic_df.reset_index(inplace = True)